// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: history.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTransfer = `-- name: CreateTransfer :exec
INSERT INTO history (id, amount, from_wallet, to_wallet)
VALUES ($1, $2, $3, $4)
`

type CreateTransferParams struct {
	ID         uuid.UUID
	Amount     float64
	FromWallet uuid.UUID
	ToWallet   uuid.UUID
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) error {
	_, err := q.db.ExecContext(ctx, createTransfer,
		arg.ID,
		arg.Amount,
		arg.FromWallet,
		arg.ToWallet,
	)
	return err
}
