// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type History struct {
	ID         uuid.UUID
	Amount     float64
	FromWallet uuid.UUID
	ToWallet   uuid.UUID
	Time       time.Time
}

type Wallet struct {
	ID        uuid.UUID
	Amount    float64
	CreatedAt time.Time
	UpdatedAt time.Time
}
